name : Run pandas job 

#when to do the job?
#Trigger the workflow
on:
  #event based trigger
  push:
    branches: 
      - main
      - master
  pull request:
    branches:
      - main
      - master
  #schedule based trigger
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

#how to do the job?
jobs:
  run-pandas-job:  #Use the name of the job
   runs on: ubuntu-latest. #specifies the operating system to run the job on. In this case, it uses the latest version of Ubuntu.
   
   steps:
    - name: Checkout code. #name of the step
      uses: actions/checkout@v2. #owner/repo@version

    